// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uulwlwnashpchdwanxnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bHdsd25hc2hwY2hkd2FueG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzU0ODcsImV4cCI6MjA3MzU1MTQ4N30.VgFVbkl4iIs2b35bDGTBOUbDB87PsGVoInxmQwv5pTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});